### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by ChanceHarrison** [Dan0sz/host-webfonts-locally#3]
The [readme.txt](https://github.com/Dan0sz/host-webfonts-locally/blob/7a4afeaf8fd08e321539ec0025f2880bc59afe69/readme.txt#L8) and header of [host-webfonts-local.php](https://github.com/Dan0sz/host-webfonts-locally/blob/7a4afeaf8fd08e321539ec0025f2880bc59afe69/host-webfonts-local.php#L9) assert that the software is provided under GPLv2 or later. This does not match with the [LICENSE](https://github.com/Dan0sz/host-webfonts-locally/blob/7a4afeaf8fd08e321539ec0025f2880bc59afe69/LICENSE#L2) file (which specifies MIT) and the [package.json](https://github.com/Dan0sz/host-webfonts-locally/blob/7a4afeaf8fd08e321539ec0025f2880bc59afe69/package.json#L10) file (which specifies ISC). Whether the differences are significant to you, I cannot say, but I thought I would raise the matter nonetheless.

**Comment by Dan0sz** [comment]
Thanks for pointing this out, will take care of this now!
